#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
dunst &

xrandr --output eDP-1 --mode 1600x900 &
xwallpaper --zoom ~/pix/wal.jpg &


bspc monitor HDMI-1 -d I II III IV V
bspc monitor eDP-1 -d VI VII VIII IX

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
#bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

bspc config border_width         0
bspc config window_gap          24
#bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config bottom_padding 0
#bspc config top_padding 20
bspc config top_padding 40

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Telegram-desktop state=floating
bspc config focus_follows_pointer true
bspc rule -a Zathura state=tiling
#From blue github bspwm config

# Remove x cursor
xsetroot -cursor_name left_ptr &

#Polybar Launching
~/.config/polybar/./launch.sh

#enable touchpad tapping and natural scrolling
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
